name: Connection to SSH

on:
  push:
    branches: [main]
  
jobs:
  deploy:
      runs-on: ubuntu-latest

      steps:

        - name: SSH into EC2 and deploy container
          uses: appleboy/ssh-action@v0.1.10
          with: 
            host: ${{ secrets.EC2_IP }}
            username: ${{ secrets.EC2_USER }}
            key: ${{ secrets.AWS_ACCESS_PEM }}
            script: |
              docker run -d \
              --name postgresql-dev\
              -e POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
              -e POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
              -e POSTGRES_DB=${{ secrets.POSTGRES_DB }} \
              -p 5432:5432 \
              postgres:15